CREATE TABLE DICTIONNAIRE (
    ID NUMBER,
    MOT VARCHAR(255) UNIQUE NOT NULL ,
    CONSTRAINT pk_INDEX PRIMARY KEY (ID)
);

CREATE TABLE MATRICE(
    IDMOT1 NUMBER,
    IDMOT2 NUMBER,
    TAILLE NUMBER,
    OCCURRENCE NUMBER,
    CONSTRAINT pk_unique PRIMARY KEY (IDMOT1,IDMOT2,TAILLE)
);

ALTER TABLE MATRICE ADD CONSTRAINT fk_idmot1 FOREIGN KEY(IDMOT1) REFERENCES DICTIONNAIRE(ID);